# Generated by Django 3.1.6 on 2021-05-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('price', models.IntegerField(max_length=240, verbose_name='Price')),
                ('description', models.CharField(max_length=240, verbose_name='Description')),
                ('image', models.ImageField(max_length=254, upload_to='photos')),
            ],
        ),
    ]
