# Generated by Django 3.1.6 on 2021-05-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210508_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='bag',
            fields=[
                ('bagId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=240, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=240, verbose_name='Model')),
                ('gender', models.CharField(blank=True, max_length=240, verbose_name='Gender')),
                ('price', models.IntegerField(blank=True, max_length=240, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Description')),
                ('image', models.ImageField(blank=True, max_length=254, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='jeans',
            fields=[
                ('jeansId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=240, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=240, verbose_name='Model')),
                ('gender', models.CharField(blank=True, max_length=240, verbose_name='Gender')),
                ('price', models.IntegerField(blank=True, max_length=240, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Description')),
                ('image', models.ImageField(blank=True, max_length=254, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='shoes',
            fields=[
                ('shoesId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=240, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=240, verbose_name='Model')),
                ('gender', models.CharField(blank=True, max_length=240, verbose_name='Gender')),
                ('price', models.IntegerField(blank=True, max_length=240, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Description')),
                ('image', models.ImageField(blank=True, max_length=254, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='sweatshirt',
            fields=[
                ('sweatshirtId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=240, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=240, verbose_name='Model')),
                ('gender', models.CharField(blank=True, max_length=240, verbose_name='Gender')),
                ('price', models.IntegerField(blank=True, max_length=240, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Description')),
                ('image', models.ImageField(blank=True, max_length=254, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='tshirt',
            fields=[
                ('tshirtId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=240, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=240, verbose_name='Model')),
                ('gender', models.CharField(blank=True, max_length=240, verbose_name='Gender')),
                ('price', models.IntegerField(blank=True, max_length=240, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Description')),
                ('image', models.ImageField(blank=True, max_length=254, upload_to='photos')),
            ],
        ),
    ]
